#!/bin/bash
# Description of this script

show_usage() {
  echo "┌─┐"
  echo "| \$ |"
  echo "└─┘"
}

main() {
  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_usage
    exit 0
  fi

  if [[ -z "$1" ]]; then
    echo "No argument provided"
    show_usage
    exit 1
  fi

  exit 0
}

main "$@"
