#!/bin/zsh

function show_usage {
    echo "┌─┐"
    echo "||"
    echo "└─┘"
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_usage
    exit 0
fi

if [[ -z "$1" ]]; then
    echo "No argument provided"
    exit 1
fi
