#!/bin/bash
# Log things I do throughout the day so I remember everything I accomplish

readonly LOG_FILE_PATH="${HOME}/Documents/vault/logs/logs.md"
readonly LOG_DIR_PATH="${HOME}/Documents/vault/logs"

show_usage() {
  echo "┌─────────────────────────┐"
  echo "| \$ new_log <log_message> |"
  echo "└─────────────────────────┘"
}

main() {
  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_usage
    exit 0
  fi

  if [[ -z "$1" ]]; then
    echo "No argument provided"
    show_usage
    exit 1
  fi

  if [[ ! -d "${LOG_DIR_PATH}" ]]; then
    mkdir "${LOG_DIR_PATH}"
    printf "\e[40;34mCreated %s\e[0m\n" "${LOG_DIR_PATH}"
  fi

  if [[ ! -e "${LOG_FILE_PATH}" ]]; then
    touch "${LOG_FILE_PATH}"
    printf "\e[40;34mCreated log.txt in %s\e[0m\n" "${LOG_DIR_PATH}"
  fi

  # local today
  # today=$(date)
  # echo "${today} ➡︎ $1" >>"${LOG_FILE_PATH}"
  exit 0
}

main "$@"
