#!/opt/homebrew/bin/bash
#

show_usage() {
  echo "┌───────────┐"
  echo "| \$ secrets |"
  echo "└───────────┘"
}

main() {
  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_usage
    exit 0
  fi

  local project_output
  project_output=$(gcloud config get-value project 2>&1)
  if [[ "${project_output}" != "proglo-secrets" ]]; then
    echo "You are not in the 'proglo-secrets' gcloud project. Please switch to the correct project."
    echo -n "gcloud config set project proglo-secrets" | pbcopy
    echo "\"gcloud config set project proglo-secrets\" has been copied to your clipboard."
    exit 1
  fi

  local secrets_list_output
  secrets_list_output=$(gcloud secrets list --format="value(name)" 2>&1)
  local -a list_of_secrets
  readarray -t list_of_secrets <<<"${secrets_list_output}"

  local -i i=0
  local steps="${#list_of_secrets[@]}"
  for ((i = 0; i < steps; i++)); do
    local secret="${list_of_secrets[i]}"
    echo "[${i}]: ${secret}"
  done

  echo "Select a secret to copy to your clipboard it's index."
  read index

  # =~ performs a regular expression match
  if ! [[ "${index}" =~ ^[0-9]+$ ]] || ((index < 0 || index >= steps)); then
    echo "Invalid index. Please enter a number between 0 and $((steps - 1))."
    exit 1
  fi

  local selected_secret="${list_of_secrets[index]}"
  local secret_value
  secret_value=$(gcloud secrets versions access latest --secret="${selected_secret}" 2>&1)
  echo -n "${secret_value}" | pbcopy
  echo "Secret '${selected_secret}' copied to clipboard."
  exit 0
}

main "$@"
